### ISSUE TITLE
Beta: Not getting some images from SD

### ISSUE THREAD

**Issue by dazedcrazy** [mar-mei/guide2go#10]
**Describe the bug**
Beta doesn't get images for some shows/movies

**Expected behavior**
Images for shows/movies

**Screenshots**
Nornal guide2go Version: 1.0.5
![image](https://user-images.githubusercontent.com/9027988/81477425-ac3c0200-920f-11ea-8d17-1101393b7c01.png)
Beta guide2go Version: 1.1.0
![image](https://user-images.githubusercontent.com/9027988/81477452-c1b12c00-920f-11ea-8e5a-0ee937d2fc47.png)

Also noticed it doesn't get the sub-title in the beta too.

**Comment by mar-mei** [comment]
I can look at it, but I need the country, the postcode, lineup, your image setting from the config and an example that was not yesterday ;)

**Comment by dazedcrazy** [comment]
The Country: UK, Postcode: SW1X, Lineup: GBR-1007913-DEFAULT
Here is the config files I used just with my SD account details removed
[guide2go.zip](https://github.com/mar-mei/guide2go/files/4605660/guide2go.zip)

**Comment by dazedcrazy** [comment]
I ran it a few more times for tests and it's started to show the images so maybe something on schedulesdirects end for images? 
It's still not adding the sub-title in the beta version though.

**Comment by mar-mei** [comment]
The issue with the icons seems to be a bug. I'll take a look at the next few days.

I looked at the EPG data from your UK lineup today, not every one has a subtitle. The SD data is stored unchanged in the cache file, some of the subtitles are already missing there.

**Comment by dazedcrazy** [comment]
Yeah some of the sub-titles are missing with **Version: 1.0.5** but **Version: 1.1.0** never has any. Even when  **Version: 1.0.5** does have one  **Version: 1.1.0** never does

**Comment by mar-mei** [comment]
The problem with the icons has been fixed.
Rebuild from source code and delete the guide2go cache file.

![Auswahl_010](https://user-images.githubusercontent.com/43099631/81703168-819ab500-946c-11ea-9a9d-b1a0b880c09a.png)
![Auswahl_011](https://user-images.githubusercontent.com/43099631/81703180-8495a580-946c-11ea-9f6f-42c39f971f33.png)

Every program has a subtitle for me

**Comment by dazedcrazy** [comment]
It's getting icons now, thank you. I think what I was seeing with the sub-title was just for movies. 
![image](https://user-images.githubusercontent.com/9027988/81723431-b877c780-947a-11ea-96e7-a0aca9318703.png)
Then the beta doesn't get the sub-title
![image](https://user-images.githubusercontent.com/9027988/81723491-cf1e1e80-947a-11ea-87ec-d6d613204dda.png)

**Comment by mar-mei** [comment]
That makes sense. There are three key words in SD that are evaluated. 
- EpisodeTitle (Used for the SubTitle)
- Description100 (Not used)
- Description1000 (Used for the Description)

I looked at the code from the old version, where Description100 was used for the subtitle if there was no EpisodeTitle.
I will change that.

**Comment by mar-mei** [comment]
Subtitle has been fixed.
Rebuild from source code and delete the guide2go cache file.

**Comment by dazedcrazy** [comment]
Sub-titles now showing up. Thank you so much
