### ISSUE TITLE
New episodes not flagged as "new" in PleX EPG

### ISSUE THREAD

**Issue by lozengenods** [mar-mei/guide2go#15]
**Describe the bug**
New episodes don't flag as "new" in PleX when using xTeVe EPG (using guide2go & SchedulesDirect). It appears to be that with new episodes there is also an empty previously-shown tag. When I remove that tag and reload everything, it flags as expected.
```
    <previously-shown></previously-shown>
    <new></new>
```

**To Reproduce**
1. Create an XML file
2. Find new episodes, which also have previously-shown tag.
3. Find episode in PleX, new tag is not displayed.
4. Remove empty previously-shown tag from original xml.
5. Reload xml in xTeVe
6. Update guide in PleX
7. Find same episode in PleX guide, new tag is now displayed.

**Expected behavior**
New tag should be displayed. 

**Screenshots**
PleX EPG: https://imgur.com/36LuScC
xTeVe EPG: https://imgur.com/BDg8Zc2

**Desktop (please complete the following information):**
xTeVe: 2.1.2
guide2go: 1.1.2
PleX: 1.19.4.2935 

**Additional context**
I wasn't sure where the bug lies -- if this is a guide2go, xTeVe, or PleX bug. Thanks for your help!

**Comment by mar-mei** [comment]
Thanks for the information. I fixed it, can you test it and let me know if it works now?

**Comment by lozengenods** [comment]
Yup! That looks like it resolved it! Thank you!
