### ISSUE TITLE
cannot unmarshal string into Go struct field

### ISSUE THREAD

**Issue by mihcox** [mar-mei/guide2go#22]
Having an issue updating the guide2go today, using schedules direct.

2021/12/15 19:14:20 [URL  ] https://json.schedulesdirect.org/20141201/lineups/USA-TX64967-X
2021/12/15 19:14:21 [ERROR] json: cannot unmarshal string into Go struct field Station.stations.broadcastLanguage of type []string
2021/12/15 19:14:21 [ERROR] json: cannot unmarshal string into Go struct field .stations.broadcastLanguage of type []string
2021/12/15 19:14:21 [G2G  ] Download Schedule: 14 Day(s)

**Comment by Danelem** [comment]
I think the error is actually from SheduleDirect:
https://forums.schedulesdirect.org/viewtopic.php?f=15&t=3178

**Comment by mihcox** [comment]
Thanks for that, all appears to be working again at this time.
