### ISSUE TITLE
SD-JSON images now require tokens

### ISSUE THREAD

**Issue by sew3521** [mar-mei/guide2go#26]
From SD's website:

Effective 2022-10-01, the Schedules Direct service will be requiring that the user token be presented for most interaction with our servers. If you are running NextPVR v6 or EPG123 v1.7.1.8 or higher then this will re-enable image downloads.

If you are a developer, please check the updated API documentation. You may also contact grabber@schedulesdirect.org if you would like to have your requests steered to a “debug” server while you are testing the addition of the token to your code.

**Comment by mar-mei** [comment]
Fixed in v1.2.0
