### ISSUE TITLE
Actor/Crew/Credits information (needed for Plex)

### ISSUE THREAD

**Issue by gelsas** [mar-mei/guide2go#5]
To have the perfect experience with PLEX and the EPG function it would be perfect if also the actor /crew/credit information could be included. Those can be get via the schedules direct api aswell.

Sorry for opening all the issues. I just found your repository here on github and your application is the perfect fit. Easy to use, lightweight and can be used on linux aswell (the application I used till now was only for windows..but with this application I can automate the procress for getting the latest epg information and import them to Plex)

This is how the actor/credit section of a <programme> looks like from the application I was using on windows:

```
 <credits>
      <director>Christoph Heininger</director>
      <actor role="Ansgar von Lahnstein">Wolfram Grandezka</actor>
      <actor role="Hagen von Lahnstein">Christoph Mory</actor>
      <actor role="Tanja von Lahnstein">Miriam Lahnstein</actor>
      <actor role="Sebastian von Lahnstein">Sebastian Schlemmer</actor>
      <actor role="Thore Hellström">Philipp Oehme</actor>
      <actor role="Caro Schulz">Katja Sieder</actor>
      <actor role="Charlie Schneider">Gabriele Metzger</actor>
      <actor role="Ricardo Mendes">Daniel Sellier</actor>
      <actor role="Dana Wolf">Diane Willems</actor>
      <actor role="Jessica Stiehl">Jana Julie Kilka</actor>
      <writer>Jens Schleicher</writer>
      <writer>Franziska Fuchs</writer>
    </credits>
```

**Comment by mar-mei** [comment]
Maybe sometime later, but it's already on the to-do list
