### ISSUE TITLE
Sub-title added to the programme description

### ISSUE THREAD

**Issue by dazedcrazy** [mar-mei/guide2go#6]
**Describe the bug**
Sub-title added to the programme description 

**Screenshots**
How it looks using guide2go
![image](https://user-images.githubusercontent.com/9027988/56169605-9b05cf00-5fd6-11e9-99f7-871aa1d86a07.png)
How it looks using xmltv
![image](https://user-images.githubusercontent.com/9027988/56169666-cdafc780-5fd6-11e9-83a6-424bf50ce169.png)

You can see guide2go adds the sub-title in brackets at the end of the description 
`[Premier League: Watford v Arsenal]`

**Comment by mar-mei** [comment]
Some apps do not show the subtitle, so it's in the description again. Very important for sports broadcasts 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dazedcrazy** [comment]
Could there maybe be a flag to remove it? I can remove it with powershell by doing 
```powershell
Get-Content "F:\github\guide2go\xmltv.xml" | Foreach-Object {$_ -replace "\[.*\]" , ""} | Set-Content "F:\github\guide2go\edited.xml"
```
but I'd rather not have to on the off chance it removes something it's not suppose to

**Comment by mar-mei** [comment]
The next time I touch the code I can implant that.  But will take some time, currently working on another project.

**Comment by mar-mei** [comment]
There is now a [Beta](https://github.com/mar-mei/guide2go/tree/beta), which can be set in the config file.
