### ISSUE TITLE
Help with setting up cron

### ISSUE THREAD

**Issue by jeremytyler662** [mar-mei/guide2go#7]
Could you assist with how to get this to run everyday with cron please?

**Comment by crichardson32** [comment]
`crontab -e

0 1 * * * /path_to/guide2go -config="/path_to_config/guide1.json"
`

**Comment by mar-mei** [comment]
Cron Example:
```
0 4 * * * /path/to/guide2go -config /path/to/guide2go/config.json
```

**Comment by agipson33** [comment]
As another option, you could use systemd and created a simple service and timer for updating twice a day.

**`/etc/systemd/system/guid2go.service`**
```
[Unit]
Description=Guide2Go
Documentation=https://github.com/mar-mei/guide2go

[Service]
Type=oneshot
ExecStart=/path/to/guide2go -config /path/to/guid2go/guide2go.yaml
```
If you need/want the XML file to be owned by a specific user/group, you can add just below the `ExecStart` line.
```
User=<user>
Group=<group>
```


**`/etc/systemd/system/guide2go.timer`**
```
[Unit]
Description=Run Guide2Go twice daily

[Timer]
OnCalendar=*-*-* 00,12:00:00
RandomizedDelaySec=43200
Persistent=true

[Install]
WantedBy=timers.target
```
