### ISSUE TITLE
go 1.12 expects a different import path convention 

### ISSUE THREAD

**Issue by ramarnat** [mar-mei/guide2go#8]
**Describe the bug**
under go 1.12, the way paths are imported has changed. So the instructions to build fail.

**To Reproduce**
```
go get github.com/mar-mei/guide2go
go: finding github.com/mar-mei/guide2go latest
go: downloading github.com/mar-mei/guide2go v0.0.0-20191011170837-e19b3e62f3fc
go: extracting github.com/mar-mei/guide2go v0.0.0-20191011170837-e19b3e62f3fc
build github.com/mar-mei/guide2go: cannot find module for path _/Users/ro/devel/gocode/pkg/mod/github.com/mar-mei/guide2go@v0.0.0-20191011170837-e19b3e62f3fc/src
```
**Expected behavior**
a built binary

**Desktop (please complete the following information):**
 - OS: osx
 - Golang: 1.12

To fix, I set "github.com/guide2go/src" instead of "./src"

**Comment by mar-mei** [comment]
There is a [beta](https://github.com/mar-mei/guide2go/tree/beta) that uses Go's "new" package manager.
